### ISSUE TITLE
Python 3.4 support

### ISSUE THREAD

**Issue by jayvdb** [samuelcolvin/pytest-toolbox#4]
Installing on Python 3.4
```
Collecting pytest-toolbox~=0.2 (from -r requirements.txt (line 14))
  Using cached pytest-toolbox-0.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-8q7j25_q/pytest-toolbox/setup.py", line 6, in <module>
        long_description = Path(__file__).resolve().parent.joinpath('README.rst').read_text()
    AttributeError: 'PosixPath' object has no attribute 'read_text'
```
https://travis-ci.org/jayvdb/coala-bears/jobs/220633286

**Comment by samuelcolvin** [comment]
3.4 is pretty old now, 3.5 and 3.6 are now released. I'm afraid therefore I don't intend to support 3.4.
